update_external_temperature:
  name: Update External Temperature
  description: Send a temperature reading from another entity to the Autoterm heater
  fields:
    temperature_entity_id:
      name: Temperature Entity
      description: Entity ID of the temperature sensor to use
      required: true
      selector:
        entity:
          domain: sensor
          device_class: temperature